
export const bookConstant = {
    GET_ALL_BOOK_REQUEST: 'GET_ALL_BOOK_REQUEST',
    GET_ALL_BOOK_SUCCESS: 'GET_ALL_BOOK_SUCCESS',
    GET_ALL_BOOK_FAIL: 'GET_ALL_BOOK_FAIL',

    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE',


}